export const recetas = {
    "rollitos-primavera": {
        "categorias": ['','Complementos'],
        "nombre": "Rollitos Primavera",
        "descripcion": "Rollitos fritos rellenos de diferentes verduras picadas al estilo juliana y carne molida.",
        "porciones": "6",
        "tiempo-preparacion": "30 minutos",
        "tiempo-coccion": "35 minutos",
        "tiempo-total": "1 hora y 5 minutos",
        "ingredientes": [
            "1 taza de harina blanca",
            "1 cucharada de fécula de maíz",
            "1 taza de agua al tiempo",
            "sal",
            "pimienta",
            "canela",
            "1/2 repollo",
            "4 zanahorias",
            "1 cabeza de brocoli grande",
            "4 calabacitas o zuccini",
            "cebolla al gusto",
            "jengibre",
            "salsa de soya",
            "carne molida de puerco o res",
            "aceite (suficiente para que los rollitos estén completamente dorados)",
        ],
        "instrucciones": [
            "Mezclar todos los ingredientes sin dejar grumos.",
            "El sartén debe estar en fuego bajo-medio. Aplicar una ligera capa de aceite con una servilleta.",
            "Con una palita de brocha, aplicar una capa delgada de la mezlca en el sartén.",
            "Dejar que la capa se cosa un poco de cada lado.",
            "Apartar las hojas de masa",
            "Cortar las verduras en pequeñas julianas (tiritas)",
            "En un wok o un sartén hondo poner un poco de aceite",
            "Acitronar cebolla, y luego la carne",
            "Unos 5 minutos después agregar el repollo, y después de otros 5 minutos agregar la zanahoria, calabaza y brocoli.",
            "Agregar la salsa de soya y mezclar hasta que las verduras estén suaves.",
            "Apartar el sartén de la fuente de calor.",
            "Envolver un poco del relleno en las hojas de masa como si fuesen burritos, envolver apretando.",
            "Poner nuestros rollitos en la olla con aceite hirviendo hasta que la masa este dorada y crocante.",
        ]
    },
    "pollo-estilo-marroqui": {
        "categorias": ['aves'],
        "nombre": "Pollo estilo Marroquí",
        "descripcion": "Pollo al estilo norteafricano con limones, frutos secos y aceitunas verdes. Se sirve con puré de papas, ensalada o cuscús. Esta receta es de un amigo de mi esposo, le mandamos saludos.",
        "porciones": "6-8",
        "tiempo-preparacion": "45 mins",
        "tiempo-coccion": "1 h. 30 mins.",
        "tiempo-total": " 2 h. 15 mins.",
        "ingredientes": [
            "1/4 cucharadita de cúrcuma molida",
            "1 cucharadita de comino molido",
            "1 cucharadita de pimentón",
            "1/2 cucharadita de jengibre molido",
            "1/2 cucharadita de cilantro molido",
            "4 cucharadas de aceite de oliva",
            "6 a 8 muslos de pollo con hueso y piel",
            "sal y pimienta al gusto",
            "2 cebollas grandes en rodajas",
            "1/2 cucharaditas de ajo picado",
            "1/2 taza de pasas",
            "1/2 taza de albaricoques secos",
            "1 taza de aceitunas verdes deshuesadas",
            "2 cucharaditas de jugo de limón",
            "2 limones pequeños en rodajas",
            "1/4 taza de cilantro fresco picado",
            "Una bandeja para hornear",
            "Papel aluminio",
        ],

        "instrucciones": [
            "Mezcle las especias en un tazón pequeño.",
            "Coloque los muslos de pollo en una bolsa grande con cierre hermético, agregue la mezcla de especias, sal, pimienta y aceite de oliva en la bolsa, agite suavemente para cubrir uniformemente toda la carne con las especias.",
            "Dejar reposar los muslos marinados en el refrigerador por 30 minutos.",
            "En un sartén, calentar el aceite de oliva con el ajo picado.",
            "Añadir al sartén el pollo con la piel hacia abajo. Cocinar durante 5 minutos por ambos lados hasta que estén dorados.",
            "Retirar el pollo del sartén, reservar.",
            "En el sartén, caramelizar la cebolla en rodajas por 5 minutos, agregar sal y pimienta.",
            "Precalentar el horno a 204°C (400°F).",
            "En la bandeja para hornear, colocar los muslos de pollo.",
            "Añade las cebollas caramelizadas, los limones en rodajas, las pasas y los albaricoques secos al molde de hornear, asegurarse que la carne de pollo no quede cubierta.",
            "Cubrir la bandeja con papel aluminio y colocar la bandeja en el horno.",
            "Hornear por 40 minutos.",
            "Retirar la bandeja del horno, destapar el papel aluminio y agrega las aceitunas verdes deshuesadas, vierte la salsa de la bandeja sobre el pollo.",
            "Colocar la bandeja en el horno (ahora sin cubrir con papel de aluminio), hornea durante otros 10 minutos..",
            "Retirar la bandeja del horno, espolvorea cilantro fresco picado por encima.",
            "Deja reposar la bandeja y la carne durante 5-10 minutos.",
            "Servir y disfrutar.",
        ]
    },

    "pavo-navideno": {
        "categorias": ['aves'],
        "nombre": "Pavo Navideño",
        "descripcion": "Pavo horneado con una mezcla de ajo y mantequilla.",
        "porciones": "7-9",
        "tiempo-preparacion": "aprox. 24 horas",
        "tiempo-coccion": "aprox. 4 horas",
        "tiempo-total": "aprox. 28 horas",
        "ingredientes": [
            "1 Pavo de 6-8 kg, preferentemente ahumado y vaciado.",
            "1 Jeringa para inyectar el pavo.",
            "2 Barras de mantequilla.",
            "Sal al gusto.",
            "Pimienta al gusto.",
            "3 cucharadas de ajo en polvo.",
            "Vino blanco o rosado.",
            "1 Bolsa para hornear.",
            "1 Molde para hornear.",
        ],

        "instrucciones": [
            "Sacar a descongelar el pavo, tomar en cuenta que por cada kilo son 4 horas de descongelación. Si el pavo pesa 6 kilos, por ejemplo, tomaría 24 horas descongelarlo. Si el pavo es ahumado, no es necesario descongelarlo completamente.",
            "Derretir la mantequilla.",
            "Agregar sal, pimienta, ajo en polvo y el vino a la mantequilla derretida y mezclar.",
            "Inyectar el pavo con la mezcla de mantequilla.",
            "Dejar reposar el pavo en el refrigerador toda la noche.",
            "Al día siguiente, meter el pavo en la bolsa para hornear y cerrarla.",
            "Precalentar el horno a 180°C (350°F).",
            "Meter el pavo al horno. Tener en cuenta que por cada medio kilo de pavo se deben hornear 20 minutos. Si el pavo pesa 6 kilos, por ejemplo, tomaría 4 horas hornearlo.",
            "Antes de sacar el pavo del horno, abrir la bolsa para hornear y dejar que se dore la piel por 10-15 minutos.",
            "Sacar el pavo del horno y dejar reposar por 10 minutos.",
            "Servir y disfrutar.",
        ]
    },
    "pescado-al-horno": {
        "categorias": ['Pescados y mariscos'],
        "nombre": "Pescado al horno",
        "descripcion": "Pescado horneado al estilo papillot, que significa cocción del alimento en un envoltorio resistente al calor, en este caso aluminio.",
        "porciones": "1",
        "tiempo-preparacion": "15 mins",
        "tiempo-coccion": "20 mins.",
        "tiempo-total": " 35 mins.",
        "ingredientes": [
            "1 filete de pescado (tilapia, huachinango, etc.)",
            "1 cucharada de cebolla en polvo",
            "2 dientes de ajo",
            "Mostaza",
            "1 papa",
            "1 calabacita o zuccini",
            "1 zanahoria",
            "1/4 de barra de mantequilla",
            "Sal y pimienta al gusto",
            "Aluminio",
        ],

        "instrucciones": [
            "Precalentar el horno a 180°C (350°F).",
            "Derretir la mantequilla.",
            "Extender el papel aluminio y poner el filete de pescado en el centro.",
            "Cortar la papa, calabacita y zanahoria en rebanadas delgadas y ponerlas sobre el pescado.",
            "Agregar sal, pimienta, ajo y cebolla en polvo a la mantequilla derretida y mezclar.",
            "Untar la mezcla de mantequilla sobre el filete de pescado.",
            "Envolver el filete y la mezcla con el papel aluminio.",
            "Meter el pescado al horno y hornear, por cada kilo, 15-20 minutos.",
            "Servir y disfrutar.",
        ]
    },
    "spaghetti-amarillo": {
        "nombre": "Spaghetti amarillo",
        "descripcion": "Spaghetti hecho con queso americano y especias. Perfecto como complemento, especialmente para milanesas.",
        "porciones": "1",
        "tiempo-preparacion": "15 mins",
        "tiempo-coccion": "20 mins.",
        "tiempo-total": " 35 mins.",
        "ingredientes": [
            "500g de spaghetti",
            "1/2 queso crema (aprox. 45g)",
            "200g de queso amarillo líquido",
            "1/4 cebolla",
            "185g de pimiento morrón (preferentemente en lata)",
            "2 cucharadas de mantequilla",
            "4 dientes de ajo picados",
            "crema y leche",
            "Sal y pimienta al gusto",
        ],

        "instrucciones": [
            "Hervir agua con sal, cebolla, y el spaghetti a cocer por 12 minutos.",
            "Colar el spaghetti y apartar.",
            "En la licuadora, poner los pimientos, el queso crema, el queso amarillo, sal, pimienta y licuar.",
            "Añadir a la mezcla en la licuadora suficiente leche y crema, licuar hasta tener una consistencia como yogurt líquido.",
            "Derretir la mantequilla en una olla, añadir el ajo cuando la mantequilla esté derretida.",
            "Añadir a la olla la salsa de queso de la licuadora.",
            "Cuando empiece a hervir, añadir el spaghetti y revolver por unos 5 minutos.",
            "Servir y disfrutar.",
        ]
    },
    "asado-de-puerco": {
        "nombre": "Asado de puerco",
        "descripcion": "El asado de puerco es un platillo típico de la región noreste de México, forma parte de la gastronomía tradicional de Nuevo León. Suele acompañarse con tortillas de maíz, arroz y frijoles refritos.",
        "porciones": "3",
        "tiempo-preparacion": "15 mins",
        "tiempo-coccion": "30 mins.",
        "tiempo-total": " 45 mins.",
        "ingredientes": [
            "5 chiles anchos",
            "5 chiles guajillos",
            "1 pieza de pierna de puerco",
            "3 cucharadas de manteca de puerco o mantequilla.",
            "1 cubo de caldo de tomate",
            "2 hojas de laurel",
            "4 dientes de ajo picados",
            "1 cebolla",
            "sal, pimienta y comino al gusto",
        ],

        "instrucciones": [
            "Cortar en cubos la pieza de pierna de puerco.",
            "Dorar los cubos de puerco en mantequilla o manteca de puerco. Cuando esten doraditos, apartar",
            "En otra olla, cocer los chiles por 10 minutos.",
            "Sacar los chiles de la olla, abrirlos y limparlos (quitarles las semillas y las venas).",
            "En la licuadora, moler con poca agua los chiles, la cebolla, el ajo y el cubo de caldo de tomate.",
            "A la carne dorada, añadirle la salsa, las hojas de laurel, el comino, la sal y pimienta, y dejar a hervir por unos 10 minutos.",
            "Servir y disfrutar.",
        ]
    },
    "crema-de-aguacate": {
        "nombre": "Crema de aguacate",
        "descripcion": "Crema hecha de aguacate y cilantro. Perfecta para acompañar tostadas y taquitos.",
        "porciones": "4",
        "tiempo-preparacion": "10 mins",
        "tiempo-coccion": "0 mins.",
        "tiempo-total": " 10 mins.",
        "ingredientes": [
            "Un manojo de cilantro (aprox. 10 ramitas)",
            "1 aguacate",
            "45g de queso crema",
            "1/4 de chile jalapeño",
            "Leche al gusto",
            "Sal al gusto",
        ],

        "instrucciones": [
            "Licuar el aguacate, cilantro, queso crema, jalapeñoy la sal .",
            "Añadir la leche a la mezcla poco a poco, hasta que vea la consistencia deseada.",
            "Servir y disfrutar.",
        ]
    },
    "masa-para-pizza": {
        "nombre": "Masa para pizza",
        "descripcion": "Masa rápida para hacer pizzas.",
        "porciones": "1",
        "tiempo-preparacion": "15 mins",
        "tiempo-coccion": "30 mins.",
        "tiempo-total": " 45 mins.",
        "ingredientes": [
            "500g de harina de trigo",
            "1/2 cucharadita de sal",
            "3 cucharadas de aceite de oliva extra virgen",
            "300mg de agua tibia",
            "14g de levadura instantánea",
            "Una bandeja redonda de 40cm de diámetro",
        ],

        "instrucciones": [
            "Mezclar todos los ingredientes en un recipiente.",
            "Tapar el recipiente con un secador de cocina un poco humedecido con agua, dejar reposar por 50 minutos.",
            "Espolvorear harina sobre una superficie limpia y seca.",
            "Precalentar el horno a 218°C (425°F).",
            "Poner la masa en la superficie enharinada.",
            "Con un rodillo enharinado, estirar la masa en forma de circulo.",
            "Poner la masa en una bandeja para hornear.",
            "Hornear en la bandeja por 30 minutos.",
            "Servir y disfrutar.",
        ]
    },
    "marshmallow-witches": {
        "categorias": ["postres"],
        "nombre": "Brujas de Malvavisco",
        "porciones": "12",
        "tiempo-preparacion": "30 mins",
        "tiempo-total": "30 mins",
        "ingredientes": [
            "3/4 taza de betún de vainilla, dividido",
            "36 mini chips de chocolate semiamargo",
            "12 malvaviscos grandes",
            "1 gota de colorante alimentario verde y naranja",
            "1/4 taza de coco rallado",
            "12 obleas de chocolate",
            "12 piezas de mini Reese's cups o chocolates mini similares.",
            "12 kisses de chocolate con leche",
            "2 bolsas pequeñas resellables tipo ziploc tamaño snack",
            "2 dullas pastelera pequeñas (opcional)"
        ],
        "instrucciones": [
            "Para la cara: Untar un poco con el betún la base de las 3 chips de chocolate (2 para ojos, 1 para nariz en cada malvavisco).",
            "Para el cabello: En una bolsa pequeña, mezclar colorante verde con unas cuantas gotas de agua", 
            "Agregar el coco en la bolsa y agitar.",
            "En un tazón pequeño, mezclar 1/3 de taza de betún con colorante verde.",
            "Cortar una pequeña abertura diagonal a la bolsa del lado opuesto a donde se cierra. Agregar la dulla pastelera con el betún restante.",
            "Glasear la mezcla de coco con betún en los lados de los malvaviscos.",
            "Para los sombreros: En otra bolsa pequeña, mezclar 3 cucharadas de betún con una gota de colorante naranja.",
            "Cortar una pequeña abertura diagonal a la bolsa del lado opuesto a donde se cierra.",
            "En el centro de la oblea, untar un poco de betún.",
            "Colocar una pieza de Resse's mini cup boca abajo en el centro de la oblea, presionar para pegarlo con el betún.",
            "Untar betún en la base de una pieza de los kisses y colocar sobre el Reese's. Colocar el sombrero con un poco de betún sobre el malvavisco.",
            "Con la bolsa de betún naranja, hacer un lazo en la base del sombrero.",
        ]
    }
}